# -*- coding: utf-8 -*-
"""oscar_awards_analysis

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qXlZLXJsaT6soD02U9ME-eLJC07zf8hD
"""

import numpy as np
import pandas as pd
import pandas_profiling

from bubbly.bubbly import bubbleplot

import plotly.offline as py
from plotly.offline import init_notebook_mode, iplot

import warnings
warnings.filterwarnings('ignore')

data=pd.read_csv('/Oscars-demographics-DFE.csv', encoding='ISO-8859-2')

data.head()

data.award.unique()

data.describe()

data.isnull().sum()

data.info

data.corr()

data.shape

data=data.drop(columns=['birthplace_gold','date_of_birth_gold','race_ethnicity_gold','religion_gold','sexual_orientation_gold','year_of_award_gold'])

data.shape

data.head(25)

profile = pandas_profiling.ProfileReport(data)
profile

award_names={'Best Director':1, 'Best Actor':2, 'Best Supporting Actor':3,'Best Actress':4, 'Best Supporting Actress':5}
data['awards']=data.award.map(award_names)

data.columns

data.head()

visualization=bubbleplot(data,x_column='awards',y_column='_trusted_judgments',bubble_column='race_ethnicity',time_column='year_of_award')
py.iplot(visualization, config={'scrollzoom': True})

pd.crosstab([data.year_of_award],data._trusted_judgments)

